# Generated by Django 3.0.6 on 2020-05-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
