# Generated by Django 3.0.6 on 2020-05-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
